#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#connect_google:
#  path: /connect/google
#  controller: 'App\Controller\GoogleController::redirectToGoogleAction'

#connect_google_check:
#  path: /connect/google/check
#  controller: 'App\Controller\GoogleController::handleGoogleCallbackAction'

#connect_facebook:
#  path: /connect/facebook
#  controller: 'App\Controller\FacebookController::redirectToFacebookAction'

#connect_facebook_check:
#  path: /connect/facebook/check
#  controller: 'App\Controller\FacebookController::handleFacebookCallbackAction'

