#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_success:
  path: /success
  controller: App\Controller\PanierProduitController::success
  methods: [GET]
app_cancel:
  path: /cancel
  controller: App\Controller\PanierProduitController::cancel
  methods: [GET]

# config/routes.yaml
search_commandes:
  path: /search-commandes
  controller: App\Controller\CommandeController::searchCommandes
  methods: [POST]

download_pdf:
  path: /reservation/{reservationId}/download-pdf
  controller: App\Controller\ProfilController::downloadPdfAction

app_search_factures:
  path: /search-factures
  controller: App\Controller\FactureController::searchFactures


